In [1]:
#jk
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [2]:
#!pip install joblib

In [3]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
    
    def _z_outcome(self, inputs, weights):      # _ -> private method
        #transfer function
        #z = w1x1 + w2x2 + w0x0
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
         #activation function
        return np.where(z > 0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        #adding bias with X
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # np.c_  -> concat
        print(f"X_with_bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1} ")
            print("--"*10)
            #FORWARD propogation
            #transfer function
            z = self._z_outcome(X_with_bias, self.weights)
            #activation function
            y_hat = self.activation_function(z)
            print(f"predicted value after the forward pass: \n{y_hat}")
            
            #calculating error
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            #BACKWARD propogation
            #updating weights
            #Wnew = Wold + (Learning_rate * (X)^T * error)
            self.weights = self.weights + (self.eta * np.dot(X_with_bias.T, self.error))
            print(f"updated weights after epoch:{epoch + 1} / {self.epochs} : \n{self.weights}")
        
        print(f"##"*10)
        
    # training -> forward propogation + backward propogation
    # prediction -> forward propogation alone
        
    #prediction
    def predict(self, X):
        # adding bias with X
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        # transfer function - passing X_with_bias and updated weights
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
        
        

In [4]:
#prepare the data
# OR gate
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR 

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [5]:
# helping to prepare the data
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X,y

In [6]:
X, y = prepare_data(df_OR)

In [7]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [8]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [9]:
ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs= EPOCHS)

model_or.fit(X, y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1 
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:1 / 10 : 
[1.74711180e-04 8.72301162e-06 9.97705327e-02]
--------------------
for epoch >> 2 
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch:2 / 10 : 
[ 0.20017471  0.20000872 -0.20022947]
--------------------
for epoch >> 3 
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:3 / 10 : 
[ 0.20017471  0.20000872 -0.10022947]
--------------------
for epoch >> 4 
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights afte

In [10]:
model_or.predict(X)

array([0, 1, 1, 1])

In [11]:
# AND gate
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)

df_AND 

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [12]:
X, y = prepare_data(df_AND)

In [14]:
ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA, epochs= EPOCHS)

model_and.fit(X, y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1 
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:1 / 10 : 
[ 0.0998411   0.09990967 -0.09995381]
--------------------
for epoch >> 2 
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:2 / 10 : 
[-1.58904712e-04 -9.03300332e-05  2.00046195e-01]
--------------------
for epoch >> 3 
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:3 / 10 : 
[0.0998411  0.09990967 0.10004619]
--------------------
for epoch >> 4 
--------------------
predicted value after the forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights afte

In [15]:
# XOR gate

XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)

df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [16]:
X, y = prepare_data(df_XOR)
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [17]:
ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA, epochs= EPOCHS)

model_xor.fit(X, y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1 
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch:1 / 10 : 
[ 0.09992989  0.10003374 -0.19995528]
--------------------
for epoch >> 2 
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch:2 / 10 : 
[-7.01124969e-05  3.37380659e-05  4.47173430e-05]
--------------------
for epoch >> 3 
--------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch:3 / 10 : 
[ 0.09992989  0.10003374 -0.19995528]
--------------------
for epoch >> 4 
--------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights a

In [ ]:
# why perceptron unable to predict the value for xor ?
    # from graphical analysis (refer notebook notes)
    # AND and OR are LINEAR. they can be linearly seperable
    # XOR is NON-LINEAR. NOT linearly seperable 
# conclusion : so perceptron is only suitable for linearly seperable dataset

# to overcome: we have to use more no. of hidden layers