In [5]:
#jk
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [4]:
#!pip install joblib

In [22]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # np.c_  -> concat
        print(f"X_with_bias: \n{X_with_bias}")
        
        
        

In [23]:
obj = Perceptron(eta=0.01, epochs=10)

In [24]:
obj.eta

0.01

In [25]:
obj.epochs

10

In [26]:
obj.weights

array([-6.23801589e-05,  1.75034812e-05,  4.56764683e-05])

In [27]:
X = np.ones((4,2))

In [28]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
y = np.ones((4,1))

In [30]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [31]:
obj.fit(X, y)

X_with_bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [7]:
#rough work
np.random.randn(3) * 1e-4

array([ 5.83164863e-05, -9.19066895e-05, -1.65025312e-05])